name: Build the game
run-name: ${{ github.actor }} has triggered a new build
jobs:
  - uses: game-ci/unity-builder@v2
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    with:
      targetPlatform: StandaloneWindows64
      unityVersion: auto
  - uses: actions/upload-artifact@v2
    with:
      name: Build
      path: build
      
