name: Build the game
run-name: ${{ github.actor }} has triggered a new build
on:
  push:
    branches:
      - main
jobs:
  BuildTheGame:
    name: Build the game for Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
          restore-keys: Library
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: auto
          versioning: Semantic
          tag: v1.0
          buildName: TheGame
          buildsPath: WindowsBuild
          projectPath: Builds
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: Builds/WindowsBuild/TheGame
