name: Build the game
run-name: ${{ github.actor }} has triggered a new build
on:
  push:
    branches:
      - main
jobs:
  BuildTheGame:
    name: Build the game for Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: StandaloneWindows64
          key: Library-MyProjectName-TargetPlatform
          restore-keys: Library-MyProjectName-TargetPlatform
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: auto
          versioning: Semantic
          tag: v1.0
          buildName: "Name Goes Here"
      - uses: actions/upload-artifact@v2
        with:
          name: "Name Goes Here"
          path: StandaloneWindows64
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
